### ISSUE TITLE
Docker JRE is not working.

### ISSUE THREAD

**Issue by theobolo** [pires/docker-jre#6]
Hello Pires,

I use a lot, your work to use logstash on my kubernetes cluster but i've noticed when i was rebuilding my own images for logstash that the lasts images of Docker JRE aren't working with Logstash.

You put the ENV JAVA_HOME /opt/java

but i think it's more something like that now : 

ENV JAVA_HOME /opt/jre

If i use your quay.io/pires/docker-jre:8u74-dns and build a docker logstash with it, logstash is not able to find the Java bin.

**Comment by pires** [comment]
Damn, I was under the impression I had fixed this. Thank you for reporting.

**Comment by theobolo** [comment]
You'r welcome :)

**Comment by pires** [comment]
No, `logstash` doesn't output a thing so it's running and you're good :)

**Comment by theobolo** [comment]
Logstash is creating an index on Elasticsearch by default in that case ?

**Comment by theobolo** [comment]
because : 

```
core@kube-00 ~/kubernetes-elk-cluster $ curl http://10.19.214.65:9200/logstash-*
{}core@kube-00 ~/kubernetes-elk-cluster $ curl http://10.19.214.65:9200/logstash-*
{}core@kube-00 ~/kubernetes-elk-cluster $
```

**Comment by pires** [comment]
@theobolo can't help you there, I'm sorry. You'll have to figure out this one yourself, because I don't know about your configuration (`logstash`, `elasticsearch`), networking (routes, firewall rules), etc. I am fixing this and moving on. Again, thank you for reporting.

**Comment by theobolo** [comment]
Thank you. Have a nice day

**Comment by pires** [comment]
@theobolo use `quay.io/pires/docker-jre:8u72` and let me know.
